// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZ8c4xs24ahjSUCFTFP5SLgH8OBnvjoU',
    appId: '1:146651723158:web:bf526c22ae8aef025859b7',
    messagingSenderId: '146651723158',
    projectId: 'portfolio-fltr-app',
    authDomain: 'portfolio-fltr-app.firebaseapp.com',
    storageBucket: 'portfolio-fltr-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_97f5DzKzp3aKkek6alPuQnT6ShOuilg',
    appId: '1:146651723158:android:6bc37b5738f1e5885859b7',
    messagingSenderId: '146651723158',
    projectId: 'portfolio-fltr-app',
    storageBucket: 'portfolio-fltr-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyru4UsJUdJrfwBy1QizIkQi8uf0QBTZk',
    appId: '1:146651723158:ios:5d527beae28503df5859b7',
    messagingSenderId: '146651723158',
    projectId: 'portfolio-fltr-app',
    storageBucket: 'portfolio-fltr-app.appspot.com',
    iosClientId: '146651723158-rbm3lbkkjn37hpq0dq3bhhpnujttahmn.apps.googleusercontent.com',
    iosBundleId: 'com.aizazhaider.portfolioApp',
  );
}
